// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This is a placeholder. The user MUST run `flutterfire configure` to generate the real file.
    throw UnimplementedError(
      'DefaultFirebaseOptions have not been configured. Run `flutterfire configure` to generate this file.',
    );
  }
}
